

from datetime import date


xmp = {
  "SourceFile": str,
  "ExifToolVersion": float,
  "FileName": str,
  "Directory": str,
  "FileSize": str,
  "FileModifyDate": date,
  "FileAccessDate": date,
  "FileCreateDate": date,
  "FilePermissions": str,
  "FileType": "XMP",
  "FileTypeExtension": "xmp",
  "MIMEType": "application/rdf+xml",
  "XMPToolkit": "Adobe XMP Core 5.6-c140 79.160451, 2017/05/06-01:08:21        ",
  "Make": str,
  "Model": str,
  "Orientation": str,
  "ImageWidth": int,
  "ImageHeight": int,
  "ExifVersion": str,
  "ExposureTime": str,
  "ShutterSpeedValue": str,
  "FNumber": float,
  "ApertureValue": float,
  "ExposureProgram": str,
  "SensitivityType": int,
  "ExposureCompensation": float,
  "MaxApertureValue": float,
  "MeteringMode": str,
  "LightSource": "Unknown",
  "FocalLength": str,
  "SensingMethod": str,
  "FileSource": "Digital Camera",
  "SceneType": "Directly photographed",
  "FocalLengthIn35mmFormat": str,
  "CustomRendered": str,
  "ExposureMode": str, # Manual
  "WhiteBalance": str, # Auto
  "SceneCaptureType": "Standard",
  "GainControl": str,
  "Contrast": str,
  "Saturation": str,
  "Sharpness": str,
  "SubjectDistanceRange": "Unknown",
  "DigitalZoomRatio": int,
  "DateTimeOriginal": date,
  "ExifImageWidth": int,
  "ExifImageHeight": int,
  "Format": "image/x-nikon-nef",
  "CreatorTool": "Ver.1.03",
  "ModifyDate": date,
  "CreateDate": date,
  "MetadataDate": date,
  "SerialNumber": int,
  "LensInfo": str,
  "Lens": str,
  "ImageNumber": int,
  "ApproximateFocusDistance": float,
  "DateCreated": date,
  "SidecarForExtension": str,
  "EmbeddedXMPDigest": str,
  "DocumentID": str,
  "PreservedFileName": str,
  "OriginalDocumentID": str,
  "InstanceID": str,
  "Version": int,
  "ProcessVersion": float,
  "ColorTemperature": int,
  "Tint": str, # int and sign in string
  "Exposure2012": float, # int and sign in string
  "Contrast2012": int, # int and sign in string
  "Highlights2012": int,
  "Shadows2012": str,
  "Whites2012": str,
  "Blacks2012": str,
  "Texture": int,
  "Clarity2012": str,
  "Dehaze": str,
  "Vibrance": str,
  "ParametricShadows": int,
  "ParametricDarks": int,
  "ParametricLights": int,
  "ParametricHighlights": int,
  "ParametricShadowSplit": int,
  "ParametricMidtoneSplit": int,
  "ParametricHighlightSplit": int,
  "SharpenRadius": "+1.0",
  "SharpenDetail": 25,
  "SharpenEdgeMasking": 75,
  "LuminanceSmoothing": 3,
  "LuminanceNoiseReductionDetail": 50,
  "LuminanceNoiseReductionContrast": 0,
  "ColorNoiseReduction": 25,
  "ColorNoiseReductionDetail": 50,
  "ColorNoiseReductionSmoothness": 50,
  "HueAdjustmentRed": 0,
  "HueAdjustmentOrange": 0,
  "HueAdjustmentYellow": 0,
  "HueAdjustmentGreen": 0,
  "HueAdjustmentAqua": 0,
  "HueAdjustmentBlue": 0,
  "HueAdjustmentPurple": 0,
  "HueAdjustmentMagenta": 0,
  "SaturationAdjustmentRed": 0,
  "SaturationAdjustmentOrange": 0,
  "SaturationAdjustmentYellow": 0,
  "SaturationAdjustmentGreen": 0,
  "SaturationAdjustmentAqua": 0,
  "SaturationAdjustmentBlue": 0,
  "SaturationAdjustmentPurple": 0,
  "SaturationAdjustmentMagenta": 0,
  "LuminanceAdjustmentRed": 0,
  "LuminanceAdjustmentOrange": 0,
  "LuminanceAdjustmentYellow": 0,
  "LuminanceAdjustmentGreen": 0,
  "LuminanceAdjustmentAqua": 0,
  "LuminanceAdjustmentBlue": 0,
  "LuminanceAdjustmentPurple": 0,
  "LuminanceAdjustmentMagenta": 0,
  "SplitToningShadowHue": 0,
  "SplitToningShadowSaturation": 0,
  "SplitToningHighlightHue": 0,
  "SplitToningHighlightSaturation": 0,
  "SplitToningBalance": 0,
  "ColorGradeMidtoneHue": 0,
  "ColorGradeMidtoneSat": 0,
  "ColorGradeShadowLum": 0,
  "ColorGradeMidtoneLum": 0,
  "ColorGradeHighlightLum": 0,
  "ColorGradeBlending": 50,
  "ColorGradeGlobalHue": 0,
  "ColorGradeGlobalSat": 0,
  "ColorGradeGlobalLum": 0,
  "AutoLateralCA": 1,
  "LensProfileEnable": 1,
  "LensManualDistortionAmount": 0,
  "VignetteAmount": 0,
  "DefringePurpleAmount": 0,
  "DefringePurpleHueLo": 30,
  "DefringePurpleHueHi": 70,
  "DefringeGreenAmount": 0,
  "DefringeGreenHueLo": 40,
  "DefringeGreenHueHi": 60,
  "PerspectiveUpright": 0,
  "PerspectiveVertical": 0,
  "PerspectiveHorizontal": 0,
  "PerspectiveRotate": 0.0,
  "PerspectiveAspect": 0,
  "PerspectiveScale": 100,
  "PerspectiveX": 0.00,
  "PerspectiveY": 0.00,
  "GrainAmount": 0,
  "PostCropVignetteAmount": -3,
  "PostCropVignetteMidpoint": 50,
  "PostCropVignetteFeather": 50,
  "PostCropVignetteRoundness": 0,
  "PostCropVignetteStyle": 1,
  "PostCropVignetteHighlightContrast": 0,
  "ShadowTint": 0,
  "RedHue": 0,
  "RedSaturation": 0,
  "GreenHue": 0,
  "GreenSaturation": 0,
  "BlueHue": 0,
  "BlueSaturation": 0,
  "OverrideLookVignette": True,
  "ToneCurveName2012": "Linear",
  "CameraProfile": "Adobe Standard",
  "CameraProfileDigest": "2FEA3EA92D5DFE77FBB77CCAD84C4769",
  "LensProfileSetup": "LensDefaults",
  "LensProfileName": str,
  "LensProfileFilename": str,
  "LensProfileDigest": str,
  "LensProfileIsEmbedded": False,
  "LensProfileDistortionScale": int,
  "LensProfileVignettingScale": int,
  "HasSettings": True,
  "AlreadyApplied": False,
  "RawFileName": str,
  "ISO": int,
  "FlashFired": bool,
  "FlashReturn": str,
  "FlashMode": str,
  "FlashFunction": bool,
  "FlashRedEyeMode": bool,
  "Creator": str,
  "Rights": str,
  "HistoryAction": str,
  "HistoryInstanceID": date,
  "HistoryWhen": date,
  "HistorySoftwareAgent": str,
  "HistoryChanged": str,
  "ToneCurvePV2012": ["0, 0","255, 255"],
  "ToneCurvePV2012Red": ["0, 0","255, 255"],
  "ToneCurvePV2012Green": ["0, 0","255, 255"],
  "ToneCurvePV2012Blue": ["0, 0","255, 255"],
  "PaintCorrectionWhat": "Correction",
  "PaintCorrectionAmount": 1.000000,
  "PaintCorrectionActive": True,
  "PaintCorrectionExposure": 0.000000,
  "PaintCorrectionHue": 0.000000,
  "PaintCorrectionSaturation": 0.000000,
  "PaintCorrectionContrast": 0.000000,
  "PaintCorrectionClarity": 0.000000,
  "PaintCorrectionSharpness": 0.000000,
  "PaintCorrectionBrightness": 0.000000,
  "PaintCorrectionToningHue": 0.000000,
  "PaintCorrectionToningSaturation": 0.000000,
  "PaintCorrectionExposure2012": -0.227000,
  "PaintCorrectionContrast2012": 0.000000,
  "PaintCorrectionHighlights2012": -0.647060,
  "PaintCorrectionShadows2012": 0.000000,
  "PaintCorrectionWhites2012": 0.000000,
  "PaintCorrectionBlacks2012": 0.000000,
  "PaintCorrectionClarity2012": 0.000000,
  "PaintCorrectionDehaze": 0.000000,
  "PaintCorrectionLuminanceNoise": 0.000000,
  "PaintCorrectionMoire": 0.000000,
  "PaintCorrectionDefringe": 0.000000,
  "PaintCorrectionTemperature": 0.000000,
  "PaintCorrectionTint": 0.000000,
  "PaintCorrectionTexture": 0.000000,
  "PaintCorrectionMaskWhat": "Mask/Paint",
  "PaintCorrectionMaskValue": 1.000000,
  "PaintCorrectionMaskRadius": 0.100945,
  "PaintCorrectionMaskFlow": 0.400000,
  "PaintCorrectionMaskCenterWeight": 0.000000,
  "PaintCorrectionMaskDabs": "d 0.142702 0.184379",
  "PaintCorrectionRangeMaskVersion": "+2",
  "PaintCorrectionRangeMaskType": 0,
  "PaintCorrectionRangeMaskColorAmount": 0.500000,
  "PaintCorrectionRangeMaskLumMin": 0.000000,
  "PaintCorrectionRangeMaskLumMax": 1.000000,
  "PaintCorrectionRangeMaskLumFeather": 0.500000,
  "PaintCorrectionRangeMaskDepthMin": 0.000000,
  "PaintCorrectionRangeMaskDepthMax": 1.000000,
  "PaintCorrectionRangeMaskDepthFeather": 0.500000,
  "LookName": "Adobe Color",
  "LookAmount": 1.000000,
  "LookUUID": "B952C231111CD8E0ECCF14B86BAA7077",
  "LookSupportsAmount": False,
  "LookSupportsMonochrome": False,
  "LookSupportsOutputReferred": False,
  "LookGroup": "Profiles",
  "LookParametersVersion": 13.3,
  "LookParametersProcessVersion": 11.0,
  "LookParametersConvertToGrayscale": False,
  "LookParametersCameraProfile": "Adobe Standard",
  "LookParametersLookTable": "E1095149FDB39D7A057BAB208837E2E1",
  "LookParametersToneCurvePV2012": ["0, 0","22, 16","40, 35","127, 127","224, 230","240, 246","255, 255"],
  "LookParametersToneCurvePV2012Red": ["0, 0","255, 255"],
  "LookParametersToneCurvePV2012Green": ["0, 0","255, 255"],
  "LookParametersToneCurvePV2012Blue": ["0, 0","255, 255"],
  "Aperture": 3.2,
  "ImageSize": "4928x3264",
  "Megapixels": 16.1,
  "ScaleFactor35efl": 1.5,
  "ShutterSpeed": "1/50",
  "Flash": "On, Return not detected",
  "CircleOfConfusion": "0.020 mm",
  "DOF": "0.18 m (1.59 - 1.78 m)",
  "FOV": "30.5 deg",
  "FocalLength35efl": str,
  "HyperfocalDistance": str,
  "LightValue": float,
  "LensID": str
}